### ISSUE TITLE
superclass mismatch for class Cipher

### ISSUE THREAD

**Issue by shanekw** [restforce/restforce#402]
updated my gems today and started getting this error:

C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::AES
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of AES was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::CAST5
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of CAST5 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::BF
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of BF was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::DES
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of DES was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::IDEA
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of IDEA was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::RC2
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of RC2 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::RC4
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of RC4 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:18: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:24: warning: already initialized constant OpenSSL::Cipher::RC5
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:24: warning: previous definition of RC5 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:28: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:33: warning: already initialized constant OpenSSL::Cipher::AES128
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:33: warning: previous definition of AES128 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:28: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:33: warning: already initialized constant OpenSSL::Cipher::AES192
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:33: warning: previous definition of AES192 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:28: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:33: warning: already initialized constant OpenSSL::Cipher::AES256
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/openssl-2.1.1/lib/openssl/cipher.rb:33: warning: previous definition of AES256 was here
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:64: warning: constant OpenSSL::Cipher::Cipher is deprecated
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:64: warning: constant OpenSSL::Cipher::Cipher is deprecated
Traceback (most recent call last):
        22: from ./lib/mygrad_salesforce_sync.rb:33:in `<main>'
        21: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/restforce-3.0.1/lib/restforce/concerns/authentication.rb:13:in `authenticate!'
        20: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/restforce-3.0.1/lib/restforce/middleware/authentication.rb:23:in `authenticate!'
        19: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:175:in `post'
        18: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:387:in `run_request'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/rack_builder.rb:143:in `build_response'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/request/url_encoded.rb:15:in `call'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/restforce-3.0.1/lib/restforce/middleware/mashify.rb:8:in `call'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'
         9: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:1455:in `request'
         8: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:909:in `start'
         7: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
         6: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:970:in `connect'
         5: from C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:970:in `require'
         4: from C:/Ruby25-x64/lib/ruby/2.5.0/openssl.rb:17:in `<top (required)>'
         3: from C:/Ruby25-x64/lib/ruby/2.5.0/openssl.rb:17:in `require'
         2: from C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:15:in `<top (required)>'
         1: from C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:16:in `<module:OpenSSL>'
C:/Ruby25-x64/lib/ruby/2.5.0/openssl/cipher.rb:64:in `<class:Cipher>': superclass mismatch for class Cipher (TypeError)

**Comment by shanekw** [comment]
issue is from faraday
