### ISSUE TITLE
INVALID_AUTH_HEADER Error

### ISSUE THREAD

**Issue by icelander** [restforce/restforce#489]
I'm pulling my hair out trying to get this to work, but I haven't found the right combination of config settings yet.

Here's my current code, using password login :

```ruby
client = Restforce.new(username: config['username'], # My email
                       password: config['password'], # Password
                       instance_url: config['instance_url'], # My instance URL
                       host: config['host'], # https://test.salesforce.com
                       security_token: config['initial_access_token'], # Salesforce Initial Access Token
                       client_id: config['client_id'], # Salesforce Consumer Key
                       client_secret: config['client_secret'], # Salesforce Consumer Secret
                       api_version: '41.0')

pp client.find('Account', '<Account ID>')
```

When I run this I get the following error:

```
/Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/middleware/raise_error.rb:13:in `on_complete': INVALID_AUTH_HEADER: INVALID_HEADER_TYPE (Restforce::UnauthorizedError)
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
	from /Library/Ruby/Gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:85:in `block in perform_with_redirection'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
	from /Library/Ruby/Gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:80:in `perform_with_redirection'
	from /Library/Ruby/Gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/middleware/instance_url.rb:13:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/middleware/authorization.rb:11:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/request/encode_json.rb:24:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/middleware/multipart.rb:16:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/middleware/mashify.rb:8:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
	from /Library/Ruby/Gems/2.3.0/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/concerns/verbs.rb:63:in `block in define_api_verb'
	from /Library/Ruby/Gems/2.3.0/gems/restforce-3.1.0/lib/restforce/concerns/api.rb:435:in `find'
	from ./salesforce.rb:29:in `<main>'
```

**Comment by icelander** [comment]
I managed to get it working with this:

```ruby
client = Restforce.new(username: config['username'], # My email
                       password: config['password'], # Password
                       instance_url: config['instance_url'], # My instance URL
                       host: config['host'], # https://test.salesforce.com
                       client_id: config['client_id'], # Salesforce Consumer Key
                       client_secret: config['client_secret'], # Salesforce Consumer Secret
                       api_version: '41.0')
```

Change `test.salesforce.com` to `login.salesforce.com` to not use the sandbox.

**Comment by nello** [comment]
Thanks for this. Still not working for me. There are just too many things that can go wrong with this library. Gotta love that none of the examples seem to include both instance_url and host, yet both appear to be necessary.

**Comment by timrogers** [comment]
Please do feel free to make a pull request to fix that!

**Comment by matt17r** [comment]
For anyone else struggling with this error, another thing to check is login restrictions. Check the profile of the user you're authenticating with ([login hours](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/login_hours.htm) and [IP Ranges](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/login_ip_ranges.htm)) and also check the [overall Network Access settings](https://help.salesforce.com/s/articleView?id=sf.security_networkaccess.htm&type=5).

I had to add my [home IP address](https://www.whatsmyip.org) to continue developing while off the college network:

<img width="996" alt="image" src="https://github.com/user-attachments/assets/56ccae61-d030-4503-91b1-2680a3af66a7">
