### ISSUE TITLE
LoadError: cannot load such file -- faraday/upload_io

### ISSUE THREAD

**Issue by philip13** [restforce/restforce#538]
Help me please, I can not upload files to may sandbox: 

Gemfile:
```
source 'https://rubygems.org'


ruby '2.3.8'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
group :development, :test do
  gem 'sqlite3', '~> 1.3.13'
end

# Use Bootstrap with Sass
gem 'bootstrap-sass', '~> 3.3.6'
# Use SCSS for stylesheets
#gem 'sass-rails', '~> 5.0'  #this version default of Refinerycms instalation
gem 'sass-rails', '>= 3.2' #this version is the version recoment to install with bootstrap sass
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc



group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

group :production do
  gem 'pg'
  gem 'dragonfly-s3_data_store'
  gem 'fog-aws'
end

gem 'restforce', '~> 3.1.0'

# Refinery CMS
gem 'refinerycms', '~> 3.0'

# Optionally, specify additional Refinery CMS Extensions here:
gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.1']
gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
gem 'refinerycms-authentication-devise', '~> 1.0'


gem 'sprockets', '~>3.7.2'

gem 'refinerycms-staff_members', path: 'vendor/extensions'
gem 'refinerycms-customers', path: 'vendor/extensions'
gem 'refinerycms-case_studies', path: 'vendor/extensions'

gem 'contentful'
gem 'redcarpet'

gem 'refinerycms-blogs', path: 'vendor/extensions'
gem 'refinerycms-values', path: 'vendor/extensions'
gem 'refinerycms-positions', path: 'vendor/extensions'
gem 'refinerycms-career_paths', path: 'vendor/extensions'
gem 'scout_apm'
gem 'newrelic_rpm'

gem 'dalli'
gem 'memcachier'

gem 'social-share-button'
gem 'bootstrap-multiselect-rails'


gem 'refinerycms-testimonials', path: 'vendor/extensions'
```

Gemfile.lock
```
PATH
  remote: vendor/extensions
  specs:
    refinerycms-blogs (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-career_paths (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-case_studies (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-customers (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-positions (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-staff_members (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-testimonials (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)
    refinerycms-values (1.0)
      acts_as_indexed (~> 0.8.0)
      refinerycms-core (~> 3.0.3)

GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.6)
      actionview (= 4.2.6)
      activesupport (= 4.2.6)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.6)
      activesupport (= 4.2.6)
      globalid (>= 0.3.0)
    activemodel (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
    activerecord (4.2.6)
      activemodel (= 4.2.6)
      activesupport (= 4.2.6)
      arel (~> 6.0)
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    acts_as_indexed (0.8.3)
    addressable (2.4.0)
    arel (6.0.3)
    autoprefixer-rails (6.3.6.2)
      execjs
    awesome_nested_set (3.0.3)
      activerecord (>= 4.0.0, < 5)
    babosa (1.0.2)
    bcrypt (3.1.11)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bootstrap-multiselect-rails (0.9.9)
      rails (>= 4.0.0)
    bootstrap-sass (3.3.6)
      autoprefixer-rails (>= 5.2.1)
      sass (>= 3.3.4)
    builder (3.2.2)
    byebug (9.0.5)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.1.4)
    contentful (2.11.1)
      http (> 0.8, < 4.0)
      multi_json (~> 1)
    dalli (2.7.10)
    debug_inspector (0.0.2)
    decorators (2.0.2)
      railties (>= 4.0.0, < 5.1)
    devise (3.5.10)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    domain_name (0.5.20180417)
      unf (>= 0.0.5, < 1.0.0)
    dragonfly (1.0.12)
      addressable (~> 2.3)
      multi_json (~> 1.0)
      rack (>= 1.3.0)
    dragonfly-s3_data_store (1.2)
      dragonfly (~> 1.0)
      fog-aws
    erubis (2.7.0)
    excon (0.49.0)
    execjs (2.7.0)
    faraday (1.0.0)
      multipart-post (>= 1.2, < 3)
    faraday_middleware (1.0.0.rc1)
      faraday (~> 1.0)
    fog-aws (0.9.2)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.40.0)
      builder
      excon (~> 0.49)
      formatador (~> 0.2)
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    font-awesome-sass (4.6.2)
      sass (>= 3.2)
    formatador (0.2.5)
    friendly_id (5.1.0)
      activerecord (>= 4.0.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    globalize (5.0.1)
      activemodel (>= 4.2.0, < 4.3)
      activerecord (>= 4.2.0, < 4.3)
    hashie (3.6.0)
    http (3.3.0)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 2.0)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.3)
      domain_name (~> 0.5)
    http-form_data (2.1.1)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    ipaddress (0.8.3)
    jbuilder (2.5.0)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    jquery-rails (4.1.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jquery-ui-rails (5.0.5)
      railties (>= 3.2.16)
    json (1.8.3)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.4)
      mime-types (>= 1.16, < 4)
    memcachier (0.0.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    multi_json (1.12.1)
    multipart-post (2.1.1)
    newrelic_rpm (6.5.0.357)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    orm_adapter (0.5.0)
    pg (0.18.4)
    pkg-config (1.1.7)
    rack (1.6.11)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.6)
      actionmailer (= 4.2.6)
      actionpack (= 4.2.6)
      actionview (= 4.2.6)
      activejob (= 4.2.6)
      activemodel (= 4.2.6)
      activerecord (= 4.2.6)
      activesupport (= 4.2.6)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.6)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-i18n (4.0.9)
      i18n (~> 0.7)
      railties (~> 4.0)
    railties (4.2.6)
      actionpack (= 4.2.6)
      activesupport (= 4.2.6)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (11.2.2)
    rdoc (4.2.2)
      json (~> 1.4)
    redcarpet (3.4.0)
    refinerycms (3.0.3)
      refinerycms-core (= 3.0.3)
      refinerycms-images (= 3.0.3)
      refinerycms-pages (= 3.0.3)
      refinerycms-resources (= 3.0.3)
    refinerycms-acts-as-indexed (2.0.1)
      acts_as_indexed (~> 0.8.0)
      decorators (~> 2.0.0)
      refinerycms-core (~> 3.0.0)
    refinerycms-authentication-devise (1.0.4)
      actionmailer (~> 4.2, >= 4.2.0)
      devise (~> 3.0, >= 3.2.4)
      friendly_id (~> 5.1.0)
      refinerycms-core (~> 3.0, >= 3.0.0)
    refinerycms-core (3.0.3)
      actionpack (>= 4.2.3, < 5.0)
      activerecord (>= 4.2.3, < 5.0)
      awesome_nested_set (~> 3.0.0)
      coffee-rails (~> 4.0, >= 4.0.0)
      decorators (~> 2.0.0)
      font-awesome-sass (>= 4.3.0, < 5.0)
      jquery-rails (>= 2.3.0)
      jquery-ui-rails (~> 5.0.0)
      railties (>= 4.2.3, < 5.0)
      refinerycms-i18n (~> 3.0.0)
      sass-rails (>= 4.0, < 5.1)
      truncate_html (~> 0.9)
      will_paginate (~> 3.0.2)
      zilch-authorisation
    refinerycms-i18n (3.0.1)
      rails-i18n (~> 4.0.1)
      routing-filter (>= 0.4.0)
    refinerycms-images (3.0.3)
      dragonfly (~> 1.0.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.3)
    refinerycms-pages (3.0.3)
      awesome_nested_set (~> 3.0.0)
      babosa (!= 0.3.6)
      friendly_id (>= 5.1.0, < 5.3)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.3)
      seo_meta (~> 2.0.0.rc.1)
      speakingurl-rails (~> 8.0.0)
    refinerycms-resources (3.0.3)
      acts_as_indexed (~> 0.8.0)
      dragonfly (~> 1.0.0)
      globalize (>= 4.0.0, < 5.2)
      refinerycms-core (= 3.0.3)
    refinerycms-wymeditor (1.0.7)
      refinerycms-core (>= 3.0.0, < 5.0)
    responders (2.2.0)
      railties (>= 4.2.0, < 5.1)
    restforce (3.1.0)
      faraday (>= 0.9.0, <= 1.0)
      faraday_middleware (>= 0.8.8, <= 1.0)
      hashie (>= 1.2.0, < 4.0)
      json (>= 1.7.5)
    routing-filter (0.5.1)
      actionpack (~> 4.2)
      activesupport (~> 4.2)
    sass (3.4.22)
    sass-rails (5.0.5)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    scout_apm (2.5.1)
    sdoc (0.4.1)
      json (~> 1.7, >= 1.7.7)
      rdoc (~> 4.0)
    seo_meta (2.0.0.rc.1)
      railties (>= 3.0.0)
    social-share-button (1.2.1)
      coffee-rails
    speakingurl-rails (8.0.2)
      railties (>= 3.1)
    spring (1.7.2)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.1.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.11)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.5)
    truncate_html (0.9.3)
    turbolinks (5.0.0)
      turbolinks-source (~> 5)
    turbolinks-source (5.0.0)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.0)
      execjs (>= 0.3.0, < 3)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.5)
    warden (1.2.6)
      rack (>= 1.0)
    web-console (2.3.0)
      activemodel (>= 4.0)
      binding_of_caller (>= 0.7.2)
      railties (>= 4.0)
      sprockets-rails (>= 2.0, < 4.0)
    will_paginate (3.0.7)
    zilch-authorisation (0.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  bootstrap-multiselect-rails
  bootstrap-sass (~> 3.3.6)
  byebug
  coffee-rails (~> 4.1.0)
  contentful
  dalli
  dragonfly-s3_data_store
  fog-aws
  jbuilder (~> 2.0)
  jquery-rails
  memcachier
  newrelic_rpm
  pg
  rails (= 4.2.6)
  redcarpet
  refinerycms (~> 3.0)
  refinerycms-acts-as-indexed (~> 2.0, >= 2.0.1)
  refinerycms-authentication-devise (~> 1.0)
  refinerycms-blogs!
  refinerycms-career_paths!
  refinerycms-case_studies!
  refinerycms-customers!
  refinerycms-positions!
  refinerycms-staff_members!
  refinerycms-testimonials!
  refinerycms-values!
  refinerycms-wymeditor (~> 1.0, >= 1.0.6)
  restforce (~> 3.1.0)
  sass-rails (>= 3.2)
  scout_apm
  sdoc (~> 0.4.0)
  social-share-button
  spring
  sprockets (~> 3.7.2)
  sqlite3
  turbolinks
  uglifier (>= 1.3.0)
  web-console (~> 2.0)

RUBY VERSION
   ruby 2.3.8p459

BUNDLED WITH
   1.17.3
```

Error
```
@client ||= Restforce.new
 => #<Restforce::Data::Client @options={:api_version=>"47.0", :username=>"felipe@softwareallies.com.felipe", :password=>"XXXXXXX", :security_token=>"XXXXXXXX", :client_id=>"3MVG9zZht.XXXXX.", :client_secret=>"XXXXXXX", :jwt_key=>nil, :host=>"test.salesforce.com", :oauth_token=>nil, :refresh_token=>nil, :instance_url=>nil, :cache=>nil, :authentication_retries=>3, :compress=>nil, :mashify=>nil, :timeout=>nil, :adapter=>:net_http, :proxy_uri=>nil, :authentication_callback=>nil, :ssl=>{}, :request_headers=>nil, :logger=>#<Logger:0x00007ff383ac3630 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x00007ff383ac35e0 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00007ff383ac3590 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDOUT>>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x00007ff383ac3518>>>, :log_level=>:debug}> 
2.4.10 :002 > url = "/Downloads/unnamed.png"
 => "/Downloads/unnamed.png" 
2.4.10 :003 > @client.create( 'Attachment', ParentId: 'a0cq0000004aIbhAAE', Description: 'Document test', Name: 'My image', Body: Restforce::UploadIO.new(File.expand_path(url, __FILE__), 'image/jpeg') )
LoadError: cannot load such file -- faraday/upload_io
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /.rvm/gems/ruby-2.4.10/gems/restforce-4.2.2/lib/restforce/upload_io.rb:3:in `<top (required)>'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from (irb):3
	from /.rvm/gems/ruby-2.4.10/gems/railties-4.2.8/lib/rails/commands/console.rb:110:in `start'
	from /.rvm/gems/ruby-2.4.10/gems/railties-4.2.8/lib/rails/commands/console.rb:9:in `start'
	from /.rvm/gems/ruby-2.4.10/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /.rvm/gems/ruby-2.4.10/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /.rvm/gems/ruby-2.4.10/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /Projects/software-allies-website-v3/bin/rails:9:in `<top (required)>'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `block in load'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /.rvm/gems/ruby-2.4.10/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:268:in `load'
	from /.rvm/rubies/ruby-2.4.10/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /.rvm/rubies/ruby-2.4.10/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by ElMonx** [comment]
The problem you have is that restforce 3.1.1 should not be using faraday 1.0.0, the dependency is for faraday ~>0.15.0, so you need to downgrade it. I don't know if there is another way to do this, but adding:

`gem 'faraday', '~> 0.15.0'`

to your Gemfile and running:

`bundle update restforce`

should do it. It will downgrade faraday_middleware to 0.14.0 too.

When faraday jumped from 0.17.0 to 1.0.0 they removed faraday/upload_io.rb breaking compatibility with restforce 3.1.0 because of the require in restforce/upload_io.rb.
