### ISSUE TITLE
Unhandled Salesforce error: MALFORMED_QUERY

### ISSUE THREAD

**Issue by scottserok** [restforce/restforce#559]
Restforce doesn't have a definition for the error code `MALFORMED_QUERY`.

I discovered this missing error code because:

- [ ] I tried to `rescue` it or refer to it in my code
- [x] I got this error back from Salesforce

I used the wrong syntax 😄 
```
client = Restforce.new
client.query("SELECT Id FROM Lead WHERE SomeField__c IS NULL")

[restforce] An unrecognised error code, `MALFORMED_QUERY` has been received from Salesforce. Instead of raising an error-specific exception, we'll raise a generic `ResponseError`. Please report this missing error code on GitHub at <https://github.com/restforce/restforce/issues/new?template=unhandled-salesforce-error.md&title=Unhandled+Salesforce+error%3A+%3Cinsert+error+code+here%3E>.
Traceback (most recent call last):
       16: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'
       15: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
       14: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
       13: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
       12: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/middleware/mashify.rb:8:in `call'
       11: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/middleware/multipart.rb:16:in `call'
       10: from /usr/local/bundle/gems/faraday_middleware-1.0.0/lib/faraday_middleware/request/encode_json.rb:26:in `call'
        9: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/middleware/authentication.rb:16:in `call'
        8: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/middleware/authorization.rb:11:in `call'
        7: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/middleware/instance_url.rb:13:in `call'
        6: from /usr/local/bundle/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:67:in `call'
        5: from /usr/local/bundle/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:79:in `perform_with_redirection'
        4: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
        3: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
        2: from /usr/local/bundle/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
        1: from /usr/local/bundle/gems/restforce-5.0.0/lib/restforce/middleware/raise_error.rb:24:in `on_complete'
Restforce::ResponseError (MALFORMED_QUERY: )
Where SomeField__c IS NULL
                  ^
ERROR at Row:1:Column:91
unexpected token: 'IS'
```

**Comment by timrogers** [comment]
@scottserok Thanks for flagging this, and sorry for the delay in spotting your issue. I'll fix this now.
