### ISSUE TITLE
NOT_FOUND error when using restforce, works when using cURL

### ISSUE THREAD

**Issue by wkirby** [restforce/restforce#579]
I have authenticated a restforce client (version 5.0.3), and it appears to authenticate properly. Calls to `authenticate` return no exceptions:

```
#<Restforce::Mash access_token="{redacted}" id="https://login.salesforce.com/id/00D6g000008Ls74EAC/{redacted} instance_url="{redacted}" issued_at="1602085692514" signature="{redacted}" token_type="Bearer">
```

All subsequent calls result in a `Restforce::NotFoundError`:

```
irb(main):011:0> client.query('select Id from Account')

Traceback (most recent call last):
       16: from /bundle/gems/restforce-5.0.3/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'
       15: from /bundle/gems/faraday-0.17.0/lib/faraday/connection.rb:138:in `get'
       14: from /bundle/gems/faraday-0.17.0/lib/faraday/connection.rb:387:in `run_request'
       13: from /bundle/gems/faraday-0.17.0/lib/faraday/rack_builder.rb:143:in `build_response'
       12: from /bundle/gems/restforce-5.0.3/lib/restforce/middleware/mashify.rb:8:in `call'
       11: from /bundle/gems/restforce-5.0.3/lib/restforce/middleware/multipart.rb:16:in `call'
       10: from /bundle/gems/faraday_middleware-0.14.0/lib/faraday_middleware/request/encode_json.rb:24:in `call'
        9: from /bundle/gems/restforce-5.0.3/lib/restforce/middleware/authentication.rb:16:in `call'
        8: from /bundle/gems/restforce-5.0.3/lib/restforce/middleware/authorization.rb:11:in `call'
        7: from /bundle/gems/restforce-5.0.3/lib/restforce/middleware/instance_url.rb:13:in `call'
        6: from /bundle/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response/follow_redirects.rb:75:in `call'
        5: from /bundle/gems/faraday_middleware-0.14.0/lib/faraday_middleware/response/follow_redirects.rb:87:in `perform_with_redirection'
        4: from /bundle/gems/faraday-0.17.0/lib/faraday/response.rb:8:in `call'
        3: from /bundle/gems/faraday-0.17.0/lib/faraday/response.rb:61:in `on_complete'
        2: from /bundle/gems/faraday-0.17.0/lib/faraday/response.rb:9:in `block in call'
        1: from /bundle/gems/restforce-5.0.3/lib/restforce/middleware/raise_error.rb:16:in `on_complete'
Restforce::NotFoundError (NOT_FOUND: The requested resource does not exist)
```

Using the `oauth_token` and `instance_url` from `client.options` to populate a cURL request, I get the expected data:

```
curl https://{redacted}.my.salesforce.com/services/data/v45.0/query\?\q=select+Id+from+Account -H "Authorization: Bearer {redacted}"

=> {"totalSize":8,"done":true,"records": [...]}
```

**Comment by wkirby** [comment]
I should add that Restforce works correctly against my sandbox environment, which is identically configured.

**Comment by wkirby** [comment]
Closing this out. I found the issue after inspecting the Restforce logs. Providing an `int` value to the API version produces an invalid URL, but does not cause auth failures. The difference between:

```
Restforce.new(..., api_version: 45)
```

And

```
Restforce.new(..., api_version: 45.0)
```

Should maybe be handled by the library.
