### ISSUE TITLE
INVALID_AUTH_HEADER when using JWT

### ISSUE THREAD

**Issue by RyanMacG** [restforce/restforce#594]
I'm trying to test an API integration we've been working on and have run into issues when connecting to our sandbox using restforce and JWT. 

I've set up the self-signed key locally, imported the keystore with it to our sandbox, set up an app using that for digital signing and pre-authorised the application.

When I try to connect however I get the issue below.

```ruby
irb(main):098:1* client = Restforce.new(jwt_key: jwt_key,
irb(main):099:1*   client_id: client_id,
irb(main):100:1* instance_url: instance_url,
irb(main):101:1*   api_version: '50.0',
irb(main):102:1*   host: 'test.salesforce.com'
irb(main):103:0> )
=> #<Restforce::Data::Client @options={:api_version=>"50.0", :username=>nil, :password=>nil, :security_token=>nil, :client_id=>"CLIENT_ID", :client_secret=>nil, :jwt_key=>"/Users/ryanmacg/code/xxxx/salesforce-middleware/jwt/server.key", :host=>"test.salesforce.com", :oauth_token=>nil, :refresh_token=>nil, :instance_url=>"https://CS84.salesforce.com", :cache=>nil, :authentication_retries=>3, :compress=>nil, :mashify=>nil, :timeout=>nil, :adapter=>:net_h...
irb(main):104:0> client.search('FIND {thing in salesforce}')
Traceback (most recent call last):
       16: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/concerns/verbs.rb:63:in `block in define_api_verb'
       15: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'
       14: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/connection.rb:198:in `get'
       13: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/connection.rb:492:in `run_request'
       12: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/rack_builder.rb:154:in `build_response'
       11: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/middleware/mashify.rb:8:in `call'
       10: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/middleware/multipart.rb:16:in `call'
        9: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/request/encode_json.rb:26:in `call'
        8: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/middleware/authorization.rb:11:in `call'
        7: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/middleware/instance_url.rb:13:in `call'
        6: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:67:in `call'
        5: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response/follow_redirects.rb:79:in `perform_with_redirection'
        4: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/response.rb:11:in `call'
        3: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/response.rb:65:in `on_complete'
        2: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/faraday-1.1.0/lib/faraday/response.rb:12:in `block in call'
        1: from /Users/ryanmacg/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/restforce-5.0.3/lib/restforce/middleware/raise_error.rb:14:in `on_complete'
Restforce::UnauthorizedError (INVALID_AUTH_HEADER: INVALID_HEADER_TYPE)
```

I'd appreciate if anyone could clear up what I'm doing wrong here as I'm struggling to resolve it myself.

**Comment by nextdayflight** [comment]
@RyanMacG I think you might have forgot `username`?

**Comment by RyanMacG** [comment]
@nextdayflight yeah you're right 🤦 , I'm now getting 
```
OpenSSL::PKey::RSAError (Neither PUB key nor PRIV key: not enough data)
```

so more digging needed to work out what's gone wrong with the keyset I've generated.
