### ISSUE TITLE
Restforce not refreshing the oauth token correctly

### ISSUE THREAD

**Issue by albandum** [restforce/restforce#755]
Hi, 

Great work again on Restforce, it's a delight to use. I just have a small issue with the token refresh middleware that doesn't see to work as intended.

I'm getting these errors : 

`Restforce::AuthenticationError (invalid_grant: expired access/refresh token (400)):`

But the way I set my client up should activate the middleware : 

```
def get_salesforce_client 
     return Restforce.new(
        oauth_token: client_auth.access_token,
        refresh_token: client_auth.refresh_token,
        instance_url: self.salesforce_instance_url,
        api_version: ENV['SALESFORCE_API_VERSION'],
        client_id: ENV["SALESFORCE_CLIENT_ID"],
        client_secret: ENV["SALESFORCE_CLIENT_SECRET"],
        authentication_callback: Proc.new do |x| 
          logger.info "SALESFORCE REAUTH NEEDED FOR #{self.email}"
          client_auth.update(access_token: x.access_token)
        end
      )
end
```

Here's what a run with this looks like : 

```
c = User.first.get_salesforce_client
c.query('SELECT Id FROM Account LImit 1')
/Users/alban/.rvm/gems/ruby-3.1.2/gems/restforce-6.0.0/lib/restforce/middleware/authentication.rb:31:in `authenticate!': invalid_grant: expired access/refresh token (400) (Restforce::AuthenticationError)
/Users/alban/.rvm/gems/ruby-3.1.2/gems/restforce-6.0.0/lib/restforce/middleware/raise_error.rb:23:in `on_complete': INVALID_SESSION_ID: Session expired or invalid (Restforce::UnauthorizedError)
RESPONSE: [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]
```

So that should just regenerate an access token by itself right ?

Thanks a lot !

**Comment by albandum** [comment]
Closing - seems to work most of the time, so it must be something on our end. Will keep investigating.
