### ISSUE TITLE
Error "not in gzip format" calling `Restforce.find`

### ISSUE THREAD

**Issue by ocarreterom** [restforce/restforce#761]
From v6.1.0 I am getting this error when calling `.find`. Other methods like `.create` are working ok.

```rb
@client = Restforce.new(
  username: "",
  client_id: "",
  instance_url: "",
  jwt_key: Base64.urlsafe_decode64(""),
  api_version: "41.0"
)

@client.find("Lead", "lead_id")
# => /app/vendor/bundle/ruby/3.1.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `initialize': not in gzip format (Zlib::GzipFile::Error)
```

Restforce version: 6.1.0

**Comment by stphnrdmr** [comment]
We're experiencing a similar error, but only after updating faraday from 1.x to 2.6 as well. Restforce 6.1 with faraday 1.x seems to be working fine.

**Comment by timrogers** [comment]
Thanks for flagging this! Could you please share the full stack trace? Or creating a PR with a failing test would be even better 😊

**Comment by stphnrdmr** [comment]
Hey @timrogers, the smallest recreation I can give you is using a new gem with this Gemfile:

```
gem 'restforce', '~> 6.1.0'
gem 'faraday', '~> 2.6.0'
```

And then this script:


```ruby
require 'Restforce'

SALESFORCE_API_VERSION = "38.0"

Restforce.log = true
Restforce.configure do |config|
  config.api_version    = SALESFORCE_API_VERSION
  config.client_id      = ENV["SALESFORCE_CLIENT_ID"]
  config.client_secret  = ENV["SALESFORCE_CLIENT_SECRET"]
  config.host           = ENV["SALESFORCE_HOST"]
  config.password       = ENV["SALESFORCE_PASSWORD"]
  config.security_token = ENV["SALESFORCE_SECURITY_TOKEN"]
  config.username       = ENV["SALESFORCE_USERNAME"]
end
client = Restforce.new
client.find(class_name, id) # I've substituted these with actual values from salesforce
```

produces this stack trace:

```
Traceback (most recent call last):
       16: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/multipart.rb:16:in `call'
       15: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/json_request.rb:49:in `call'
       14: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/authentication.rb:16:in `call'
       13: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/authorization.rb:11:in `call'
       12: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/instance_url.rb:13:in `call'
       11: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:65:in `call'
       10: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:77:in `perform_with_redirection'
        9: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/raise_error.rb:9:in `call'
        8: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/json_response.rb:43:in `call'
        7: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:14:in `call'
        6: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/faraday-2.6.0/lib/faraday/response.rb:42:in `on_complete'
        5: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:15:in `block in call'
        4: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:20:in `on_complete'
        3: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `decompress'
        2: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `new'
        1: from .rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `initialize'
Zlib::GzipFile::Error (not in gzip format) 
```

**Comment by stphnrdmr** [comment]
I just tested the above gem with ruby 3.0.3 and that's also failing with a similar stack trace:

```
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `initialize'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `new'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `decompress'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:20:in `on_complete'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:15:in `block in call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-2.6.0/lib/faraday/response.rb:42:in `on_complete'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:14:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/json_response.rb:43:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/raise_error.rb:9:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:77:in `perform_with_redirection'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:65:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/instance_url.rb:13:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/authorization.rb:11:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/authentication.rb:16:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/json_request.rb:49:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/multipart.rb:16:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/mashify.rb:8:in `call'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-2.6.0/lib/faraday/rack_builder.rb:153:in `build_response'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-2.6.0/lib/faraday/connection.rb:445:in `run_request'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/faraday-2.6.0/lib/faraday/connection.rb:200:in `get'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/concerns/verbs.rb:63:in `block in define_api_verb'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/concerns/api.rb:439:in `find'
.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `initialize': not in gzip format (Zlib::GzipFile::Error)
```

**Comment by schm** [comment]
The problem is caused by this method returning true all the time

https://github.com/restforce/restforce/blob/4da1c903136b5ec7ad1a430a6ad5921641ea2113/lib/restforce/middleware/gzip.rb#L24-L26

Somehow the response headers "suddenly" always include `Content-Encoding: gzip` even though the content isn't zipped (anymore). The error started to happen when applying the following Gem update to our service:

```diff
-    faraday (2.4.0)
-      faraday-net_http (~> 2.0)
+    faraday (2.6.0)
+      faraday-net_http (>= 2.0, < 3.1)

-    faraday-net_http (2.1.0)
+    faraday-net_http (3.0.2)
```

------------

While this is not a solution, we've worked around the issue by enabling compression in Restforce:

```ruby
Restforce.configure do |config|
  config.compress = true
end
```

**Comment by rafalyesware** [comment]
Here's another stack trace from Ruby 3.0.4, looks very very similar to the one above except in this case it's a `query` vs. a `find`:

```
["/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `initialize'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `new'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `decompress'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:20:in `on_complete'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:15:in `block in call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/faraday-2.6.0/lib/faraday/response.rb:42:in `on_complete'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:14:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/json_response.rb:43:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/raise_error.rb:9:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:77:in `perform_with_redirection'",
 "/app/vendor/bundle/ruby/3.0.0/gems/faraday-follow_redirects-0.3.0/lib/faraday/follow_redirects/middleware.rb:65:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/instance_url.rb:13:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/authorization.rb:11:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/authentication.rb:16:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/json_request.rb:49:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/middleware/multipart.rb:16:in `call'",
 "/app/vendor/bundle/ruby/3.0.0/gems/faraday-2.6.0/lib/faraday/rack_builder.rb:153:in `build_response'",
 "/app/vendor/bundle/ruby/3.0.0/gems/faraday-2.6.0/lib/faraday/connection.rb:445:in `run_request'",
 "/app/vendor/bundle/ruby/3.0.0/gems/faraday-2.6.0/lib/faraday/connection.rb:200:in `get'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/concerns/verbs.rb:63:in `block in define_api_verb'",
 "/app/vendor/bundle/ruby/3.0.0/gems/restforce-6.1.0/lib/restforce/concerns/api.rb:186:in `query'",
```

I thought we had already configured our clients to set `compress: true`, but I will verify that.

**Comment by rafalyesware** [comment]
> I thought we had already configured our clients to set `compress: true`, but I will verify that.

Ah, we use `restforce` in two apps -- one sets `compress: true`, while the other does not.  Now I can confirm that the following:

````
Restforce.configure do |config|
  config.compress = true
end
```

does indeed make this work again with `faraday` v2.6.0 and `faraday-net_http` v3.0.2 (and without that, it breaks like mentioned above).

**Comment by drgcms** [comment]
I can confirm this error on Rails 7.0.4, Ruby 3.1.2 and Restforce gem 6.1.0. 

/./ruby/3.1.0/gems/restforce-6.1.0/lib/restforce/middleware/gzip.rb:30:in `initialize': not in gzip format (Zlib::GzipFile::Error)

Reverting to the previous version of restforce resolves the problem.

by
TheR

**Comment by WolfEkk** [comment]
If it's of any help it the solution provided by @rafalyesware (https://github.com/restforce/restforce/issues/761#issuecomment-1335967126) seems to work in combination with ENV based configuration. (using ENV for all else and adding the provided snippet to `application.rb`)

**Comment by rafalyesware** [comment]
> If it's of any help ~it~ the solution provided by @rafalyesware ([#761 (comment)](https://github.com/restforce/restforce/issues/761#issuecomment-1335967126)) seems to work in combination with ENV based configuration. (using ENV for all else and adding the provided snippet to `application.rb`)

Credit where credit is due, I was just confirming @schm's suggestion from https://github.com/restforce/restforce/issues/761#issuecomment-1329012277

**Comment by timrogers** [comment]
👋🏻 Sorry for the delay in looking at this! 

Could you give my potential solution a try, and let me know how you get on https://github.com/restforce/restforce/pull/779? You can set up Bundler to install the gem from Git with something like this:

```
gem 'restforce', github: 'restforce/restforce', branch: 'fix-761'
```

What I don't understand is why we are getting a `Content-Encoding` header back when the content is not encoded. I am wondering if Salesforce is doing something weird - but this should fix it.

**Comment by schm** [comment]
@timrogers thanks for looking into it.

I was able to test your changes locally and the issue seems to be resolved. Both `#query` and `#find` worked as expected with and without explicitly enabling the compression.

**Comment by timrogers** [comment]
> @timrogers thanks for looking into it.
> 
> I was able to test your changes locally and the issue seems to be resolved. Both `#query` and `#find` worked as expected with and without explicitly enabling the compression.

That's good enough for me! I'll ship it now. I would be keen to understand why this is happening, but without my own Salesforce license, it's hard to debug. I have contacted them trying to get a free license 😅
