### ISSUE TITLE
Unhandled Salesforce error: Restforce::UnauthorizedError: INVALID_AUTH_HEADER: INVALID_HEADER_TYPE

### ISSUE THREAD

**Issue by krishnananddwivedi** [restforce/restforce#811]
Here's my current code, using JWT Bearer Token
 login :

```
client = Restforce.new(username: 'my user name', # My user name
                       client_id: 'client_id', #consumer key of the connected app
                       instance_url: 'instance_url', # My instance URL
                       jwt_key: 'certificate_private_key', #private key of the certificate uploaded to the connected app
                       api_version: '55.0')
```

`client.user_info`
When I run this I get the following error:

```
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/middleware/raise_error.rb:13:in `on_complete'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday-0.17.5/lib/faraday/response.rb:9:in `block in call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday-0.17.5/lib/faraday/response.rb:61:in `on_complete'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday-0.17.5/lib/faraday/response.rb:8:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/middleware/instance_url.rb:13:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/middleware/authorization.rb:11:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/request/encode_json.rb:24:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/middleware/multipart.rb:16:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/middleware/mashify.rb:8:in `call'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday-0.17.5/lib/faraday/rack_builder.rb:143:in `build_response'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday-0.17.5/lib/faraday/connection.rb:387:in `run_request'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/faraday-0.17.5/lib/faraday/connection.rb:138:in `get'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/concerns/verbs.rb:37:in `block in define_verb'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/concerns/verbs.rb:63:in `block in define_api_verb'
ruby/2.7.7/lib/ruby/gems/2.7.0/gems/restforce-3.0.1/lib/restforce/concerns/api.rb:45:in `user_info'
```

**Comment by krzcho** [comment]
getting same error when using:

    @client = Restforce.new(
      instance_url: ENV['SALESFORCE_INSTANCE_URL'],
      username: ENV['SALESFORCE_USERNAME'],
      password: ENV['SALESFORCE_PASSWORD'],
      security_token: ENV['SALESFORCE_SECURITY_TOKEN']
    )

**Comment by timrogers** [comment]
@krzcho Can you share the full error output please?

**Comment by krzcho** [comment]
@timrogers sure

app/services/salesforce_service.rb:12:in `query': INVALID_AUTH_HEADER: INVALID_AUTH_HEADER (Restforce::UnauthorizedError)
RESPONSE: [{"message":"INVALID_AUTH_HEADER","errorCode":"INVALID_AUTH_HEADER"}]
        from app/services/salesforce_service.rb:31:in `query2'
        from (irb):2:in `<main>'

the same set of parameters (instance, username, password and token) work fine in python's simple_salesforce

**Comment by timrogers** [comment]
Can you try adding `Restforce.log = true`? I'm hoping you'll get some debugging logging from it.

**Comment by krzcho** [comment]
Thx, I see it tries to use OAuth

headers: {"User-Agent"=>"Faraday v2.9.2", "Authorization"=>"OAuth "}

what should be the correct value for password with a token and how to enforce it?

**Comment by timrogers** [comment]
My guess is that you're using a combination of authetication options which don't work together, but I'm not 100% sure.

**Comment by matt17r** [comment]
For anyone else struggling with this error, another thing to check is login restrictions. Check the profile of the user you're authenticating with ([login hours](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/login_hours.htm) and [IP Ranges](https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/login_ip_ranges.htm)) and also check the [overall Network Access settings](https://help.salesforce.com/s/articleView?id=sf.security_networkaccess.htm&type=5).

I had to add my [home IP address](https://www.whatsmyip.org) to continue developing while off the college network:

<img width="996" alt="image" src="https://github.com/user-attachments/assets/56ccae61-d030-4503-91b1-2680a3af66a7">

**Comment by lpwanw** [comment]
I ran into an issue where the security_token was combined with my password, causing the request to fail.

This request didn't work:

grant_type=password&client_id=`id`&client_secret=`secret`&username=xxx%40gmail.com&password=`xxx`security+token

It worked when I excluded the security_token or set it to nil:

```ruby
Restforce.new(username: 'xxx@gmail.com',
                       password: "password",
                       instance_url: instance_url,
                       client_id: client_id,
                       client_secret: client_secret, 
                       security_token: nil,
                       api_version: '55.0')
```
