### ISSUE TITLE
Unhandled Salesforce error: <Faraday::ParsingError>

### ISSUE THREAD

**Issue by taman9333** [restforce/restforce#860]
Restforce doesn't have a definition for the error code
```
Faraday::ParsingError: Empty input (after ) at line 6, column 2 [parse.c:1119] in '





<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Unable to Process Request</title>
        <link  href="/dCSS/Theme2/default/maintenance.css" type="text/css" rel="stylesheet" >
    </head>

    <body>
        <div id="red">
            <div id="box">
                <h1>Unable to Process Request</h1>
                <h2>We apologize for the inconvenience</h2>
                <br><br>
                The salesforce.com servers are temporarily unable to respond to your request.  We apologize for the inconvenience.<br>
                Thank you for your patience, and please try again in a few moments.
                <br><br>
                Visit <a href=http://trust.salesforce.com>http://trust.salesforce.com</a> for current system status and availability.
                <br><br>
                <form><p class="input"><a href="javascript:history.back()" class="back">back</a><span>&nbsp;</span></form>
            </div>
        </div>

    </body>
</html>
```

I discovered this missing error code because:
I got this error while using PushTopic & not sure what's the issue or how to resolve it. Also I wanna mention that I have a bunch of customers that I use restforce PushTopic to get updates from their SF instance.

logic is encapsulated in a method like that
```ruby
def perform
  EM.run do
    begin
      customer_clients.each do |client|
        subscribe(client)
      end
    rescue StandardError => e
      Sentry.capture_exception(e)
    end
  end
end

def subscribe(client)
  client.subscription("/topic/#{topic_name}", replay: -1) do |message|
    ## some logic
  end
end
```

and the above error is not rescued & will make my application to shutdown

- [ ] I tried to `rescue` it or refer to it in my code
- [ ] I got this error back from Salesforce

**Comment by timrogers** [comment]
It looks like we need to handle the case where Salesforce returns an HTML error page, which we don't expect today.

What I can't answer is why you're getting this error. Is it reproducible every time?

**Comment by timrogers** [comment]
> [@timrogers](https://github.com/timrogers) Thanks for quick reply, the probability of this error is not high to be honest, but it would be really good if restforce gem can handle it.

Have you just seen this happen once? So it's a rare thing, not an every time thing?

> However I would say the big issue I have here is that this error is not rescued & my application will shutdown, do you know why; although I use `rescue`
> 
> rescue StandardError => e
>   Sentry.capture_exception(e)
> end

It's hard to say. Can you share some of your code so I can see where that `rescue` is?

**Comment by taman9333** [comment]
> Have you just seen this happen once? So it's a rare thing, not an every time thing?

Today, I encountered this error twice for two different customers, but I can't determine its probability at the moment. It may require more time to assess accurately. However, it seems that this error doesn't have a high probability.

**Comment by taman9333** [comment]
@timrogers Here's the code; I skipped some methods for sensitivity
```ruby
class WebsocketConsumer
  def initialize
    @alive = true
    @delay = 1
  end

  def perform
    EM.run do
      begin
        subscribe_existing_integrations
        accept_incoming_integrations
      rescue StandardError => e
        Sentry.capture_exception(e)
      end
    end
  end

  def stop
    @alive = false
  end

  private

  def subscribe_existing_integrations
    integration_map.each do |integration, client|
      subscribe_integration(client, integration)
    rescue StandardError => e
      Sentry.capture_exception(e)
    end
  end

  def accept_incoming_integrations
    Thread.new do
      ActiveRecord::Base.connection_pool.with_connection do
        while alive
          sleep delay
          subscribe_new_integration(new_integration_id)
        end
        EM.stop_event_loop
      end
    end
  end

  def new_integration_id
    cache_redis.rpop(redis_websocket_consumer_key)
  end

  def subscribe_integration(client, integration)
    client.authenticate!
    ::Salesforce::ClientSubscriber.new(client, integration).subscribe
  end
end

module Salesforce
  class ClientSubscriber
    include LoggingHelper

    def initialize(client, integration)
      @client = client
      @integration = integration
    end

    def subscribe
      client.subscription(
        "/topic/#{salesforce_push_topic_prefix}_Account", replay: -1
      ) do |message|
        method(:dispatch).curry[integration_object][message]
        logging(integration.customer_id, message_content: message)
      end
    end

    private

    attr_reader :client, :integration

    def dispatch(klass, message)
      redis.sadd("#{integration.id}", message['sobject']['Id'])
    rescue StandardError => e
      Sentry.capture_exception(e)
    end

    def redis
      # redis_client
    end
  end
end

```

**Comment by taman9333** [comment]
@timrogers Okay, I found why this error is not being rescued.

So, in the perform method:

```ruby
def perform
  EM.run do
    begin
      subscribe_existing_integrations
      accept_incoming_integrations
    rescue StandardError => e
      Sentry.capture_exception(e)
    end
  end
end
```

subscribe_existing_integrations and accept_incoming_integrations will run successfully without any error. However, when we receive an error from the Salesforce stream, such as a parsing error, it causes the application to crash.

To handle errors that occur during the runtime of syncing streams, I suggest something like this:

```ruby
def perform
  EM.run do
    subscribe_existing_integrations
    accept_incoming_integrations
  end
rescue StandardError => e
  Sentry.capture_exception(e)
end
```

However, I have a question: the modified version above would rescue from the mentioned error, but will the client for the customer I encountered this error with still be healthy and receive future updates? If not, is there an efficient or good way to subscribe again?

**Comment by taman9333** [comment]
here's another error I faced yesterday
```
Faraday::ParsingError: Empty input (after ) at line 1, column 1 [parse.c:1119] in '<html>
<body>
<center>
	<table bgcolor="white" cellpadding="0" cellspacing="0" width="758">
		<tbody>
		<tr>
			<td><span style="font-family: Verdana; font-size: medium; font-weight: bold;">We are down for maintenance.</span><br><br>Sorry for the inconvenience. We'll be back shortly.</td><br>
		</tr>
		</tbody>
	</table>
</center>
</body>
</html>
/usr/local/bundle/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response/parse_json.rb:13:in `parse'
/usr/local/bundle/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response/parse_json.rb:13:in `block in <class:ParseJson>'
/usr/local/bundle/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:54:in `parse'
/usr/local/bundle/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:43:in `process_response'
/usr/local/bundle/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:37:in `block in call'
/usr/local/bundle/gems/faraday-1.8.0/lib/faraday/response.rb:59:in `on_complete'
/usr/local/bundle/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
/usr/local/bundle/gems/restforce-5.1.1/lib/restforce/middleware/mashify.rb:8:in `call'
/usr/local/bundle/gems/faraday-1.8.0/lib/faraday/request/url_encoded.rb:25:in `call'
/usr/local/bundle/gems/faraday-1.8.0/lib/faraday/rack_builder.rb:154:in `build_response'
/usr/local/bundle/gems/faraday-1.8.0/lib/faraday/connection.rb:516:in `run_request'
/usr/local/bundle/gems/faraday-1.8.0/lib/faraday/connection.rb:281:in `post'
/usr/local/bundle/gems/restforce-5.1.1/lib/restforce/middleware/authentication.rb:24:in `authenticate!'
/usr/local/bundle/gems/restforce-5.1.1/lib/restforce/concerns/authentication.rb:13:in `authenticate!'
/usr/local/bundle/gems/restforce-5.1.1/lib/restforce/concerns/streaming.rb:45:in `block (2 levels) in faye'
/usr/local/bundle/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:39:in `block in emit'
/usr/local/bundle/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:38:in `each'
/usr/local/bundle/gems/websocket-driver-0.7.5/lib/websocket/driver/event_emitter.rb:38:in `emit'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/protocol/dispatcher.rb:166:in `handle_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/transport.rb:114:in `block in handle_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/transport.rb:113:in `each'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/transport.rb:113:in `handle_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/http.rb:23:in `block in request'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/em/deferrable.rb:158:in `set_deferred_status'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/em/deferrable.rb:198:in `fail'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/client.rb:123:in `on_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/protocol/dispatcher.rb:146:in `block in handle_error'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/em/deferrable.rb:48:in `callback'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/protocol/dispatcher.rb:145:in `handle_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/transport.rb:114:in `block in handle_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/transport.rb:113:in `each'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/transport.rb:113:in `handle_error'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/http.rb:72:in `handle_response'
/usr/local/bundle/gems/faye-1.4.0/lib/faye/transport/http.rb:18:in `block in request'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/em/deferrable.rb:151:in `set_deferred_status'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/em/deferrable.rb:191:in `succeed'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/client.rb:113:in `unbind'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/client.rb:71:in `on_request_complete'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/http_connection.rb:204:in `block in post_init'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/http_connection.rb:219:in `<<'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/http_connection.rb:219:in `receive_data'
/usr/local/bundle/gems/em-http-request-1.1.7/lib/em-http/http_connection.rb:26:in `receive_data'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
/usr/local/bundle/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
/usr/local/bundle/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:23:in `block in execute'
/usr/local/bundle/gems/sentry-ruby-core-4.7.3/lib/sentry/hub.rb:158:in `with_background_worker_disabled'
/usr/local/bundle/gems/sentry-ruby-core-4.7.3/lib/sentry/rake.rb:22:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/cli.rb:492:in `exec'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/cli.rb:28:in `start'
/usr/local/bundle/gems/bundler-2.4.18/exe/bundle:37:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.4.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.4.18/exe/bundle:29:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by taman9333** [comment]
Looking at the above logs, I believe the issue occurs when the transport:down event is triggered. At that point, we attempt to [reset the auth token](https://github.com/restforce/restforce/blob/main/lib/restforce/concerns/streaming.rb#L45); however, the authenticate! function returns an error, as mentioned in the comment above, causing the application to crash.

I'm not very familiar with the CometD/Bayeux protocol, but I understand that Faye handles reconnection. I suspect that we utilize the transport:down handler to reset the token during reconnection.

Does this explanation make sense? If so, is there a recommended approach for handling this situation properly, or is it preferable to allow the application to crash and rely on Kubernetes to restart the pod?

**Comment by taman9333** [comment]
[For this line of code](https://github.com/restforce/restforce/blob/main/lib/restforce/concerns/streaming.rb#L45) Can we implement a retry mechanism with exponential backoff to avoid this issue ?

**Comment by taman9333** [comment]
here's another errors I encountered

```
Empty input (after ) at line 1, column 1 [parse.c:1119] in 'upstream connect error or disconnect/reset before headers. reset reason: remote connection failure, transport failure reason: delayed connect error: 111
```

another one

```
Faraday::ParsingError
Empty input (after ) at line 1, column 1 [parse.c:1119] in '<html>
<body>
<center>
	<table bgcolor="white" cellpadding="0" cellspacing="0" width="758">
		<tbody>
		<tr>
			<td><span style="font-family: Verdana; font-size: medium; font-weight: bold;">We are down for maintenance.</span><br><br>Sorry for the inconvenience. We'll be back shortly.</td><br>
		</tr>
		</tbody>
	</table>
</center>
</body>
</html>
```
