### ISSUE TITLE
Unhandled Salesforce error: <insert error code here>

### ISSUE THREAD

**Issue by ccgomezn** [restforce/restforce#889]
Restforce doesn't have a definition for the error code `INSERT ERROR CODE HERE`.

Error: wrong number of arguments (given 2, expected 0..1)
Backtrace:
/usr/local/bundle/gems/restforce-6.2.4/lib/restforce/middleware/json_response.rb:22:in `initialize'
/usr/local/bundle/gems/faraday-1.10.0/lib/faraday/dependency_loader.rb:21:in `new'
/usr/local/bundle/gems/faraday-1.10.0/lib/faraday/dependency_loader.rb:21:in `new'

I discovered this missing error code because:

- [X] I tried to `rescue` it or refer to it in my code
- [ ] I got this error back from Salesforce

**Comment by timrogers** [comment]
Thanks for flagging this! Does it happen every time you try to use Restforce, or is it a rare edge case?

**Comment by handzlikt** [comment]
Hi, this happens every time after upgrading from 5.3.1 to 6.2.4.

**Comment by timrogers** [comment]
Thanks! I am guessing this is an incompatibility either your Faraday version, which is quite old. 

We do test older versions in our CI pipeline - but I wonder if there might be an issue with your very specific version. 

Would you be able to try a later patch version of Faraday v1.10?

**Comment by handzlikt** [comment]
Thank you for your quick response. It worked with Faraday 1.10.3! I've didn't notice there is a new patch version. Thank you!

**Comment by timrogers** [comment]
Great! ❤️ Badically, I think this is a Faraday bug under the hood because v1.9 works and v1.10.3 is fine too. 

I don't think it is possible to block a specific version with the gemspec. I will look into that, and if it isn't possible, I can make the gem just raise an error.

**Comment by timrogers** [comment]
I just asked ChatGPT and it looks like it is possible, so I can just block this patch version 🥳

**Comment by timrogers** [comment]
Interestingly, it looks like this is fine in the current Restforce version: https://github.com/restforce/restforce/pull/890

I'm not sure what the story is here and what exactly we can do to make things better, but I'm glad you're unblocked!
