### ISSUE TITLE
Apex REST call returning primitive value fails

### ISSUE THREAD

**Issue by stomita** [restforce/restforce#91]
When calling Apex REST call which returns simple primitive value (like Integer or String, not object) will fail in parsing.

e.g.

```
// Apex Class
@RestResource(urlMapping='/aaa/*')
global class PrimitiveTest {
    @HttpGet
    global static Integer doGet() {
        return 123;
    }
}
```

The code below will fail

```
client = Restforce.new(:username => "...", :password => "...", ...)
client.get "/services/apexrest/aaa/"
```

and outputs following stack trace

```
Faraday::Error::ParsingError: 757: unexpected token at '123'
        from /Users/stomita/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from /Users/stomita/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/json/common.rb:155:in `parse'
        from /Users/stomita/.rvm/gems/ruby-2.0.0-p247/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
...
```

**Comment by mintotsai** [comment]
I had a similar issue and was able to solve with a response middleware. My example below for others. If this can be better, please let me know.

```
module MyFaraday
  module Middleware
    class JSONString < Faraday::Response::Middleware
      def on_complete(env)
        env[:body].gsub!(/^\"|\"?$/, '')
        env[:body].gsub!(/\\"/, '"')
      end
    end
  end
end

#...

Faraday::Response.register_middleware :json_string => lambda { MyFaraday::Middleware::JSONString } 
restforceClient = Restforce.new
restforceClient.middleware.response :json_string
```
